I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 254, in script
    Ben Intro Hel Spk Si "Hello! My name is Benjamin Shu."
Exception: Sayer 'Ben' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 254, in script
    Ben Intro Hel Spk Si "Hello! My name is Benjamin Shu."
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'Ben' is not defined.

Windows-8-6.2.9200
Ren'Py 7.1.1.929
SBU Senior Project 1.0
Mon Dec 31 17:46:02 2018
