I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_b_WeekLoop.rpy", line 91, in script
    $ renpy.set("ARS_%s" % ARS_deadlines[week_num], ARS_progress)
  File "game/script_b_WeekLoop.rpy", line 91, in <module>
    $ renpy.set("ARS_%s" % ARS_deadlines[week_num], ARS_progress)
AttributeError: 'module' object has no attribute 'setValue'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_b_WeekLoop.rpy", line 91, in script
    $ renpy.set("ARS_%s" % ARS_deadlines[week_num], ARS_progress)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\ast.py", line 881, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script_b_WeekLoop.rpy", line 91, in <module>
    $ renpy.set("ARS_%s" % ARS_deadlines[week_num], ARS_progress)
AttributeError: 'module' object has no attribute 'setValue'

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
SBU Senior Project 1.0
Wed Feb 13 15:38:32 2019
